version: 2 # Use 2, or 2.1 for beta new features
jobs:
  test:
    docker:
      - image: circleci/node:10
    working_directory: ~/project
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-{{ checksum "package.json" }}
      - run: npm install
      - run: npm test
      - save_cache:
          key: v1-{{ checksum "package.json" }}
          paths:
            - node_modules
  build:
    docker:
      - image: circleci/node:10
    working_directory: ~/project
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-{{ checksum "package.json" }}
      - run: npm install
      - run: npm run build
      - persist_to_workspace:
          root: ~/project
          paths:
            - build
  deploy:
    docker:
      - image: circleci/node:10
    working_directory: ~/project
    steps:
      - attach_workspace:
          at: ~/project
      - run: sudo npm install -g --unsafe-perm now
      - run: now --token $NOW_TOKEN deploy ~/project/build

workflows:
  version: 2 # version is curently 2
  main_workflow: # name of workflow
    jobs:
      - test
      - build:
          requires:
            - test
      - deploy:
          requires:
            - build
