version: 2
  build:
    docker:
      - image: circleci/node:10
    working_directory: ~/project
    steps: 
      - checkout 
      - run: npm install
      - run: npm test
      - run: npm build

workflows:
  version: 2 # version is curently 2
  main_workflow: # name of workflow
    jobs:
      - build
